version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install -g yarn
      - npm install -g esbuild-runner
      # - npm 
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment.zip . -x "/*.git/*"
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name testappFunction --zip-file fileb://deployment.zip
      - echo "DONE!!"
